# Generated by Django 4.2.21 on 2025-05-17 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, help_text='Le projet est-il visible publiquement ? (True = tous les entrepreneurs peuvent le voir)')),
                ('title', models.CharField(help_text='Titre clair et court du projet (ex. : Rénovation salle de bain)', max_length=255)),
                ('description', models.TextField(help_text='Description complète des travaux à réaliser')),
                ('category', models.CharField(help_text='Type de projet ou domaine requis (ex : Électricité, Peinture)', max_length=100)),
                ('location', models.CharField(help_text="Lieu d'exécution des travaux (ville, région, etc.)", max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget estimé ou alloué pour le projet (en dollars CAD)', max_digits=10)),
                ('deadline', models.DateField(help_text='Date limite souhaitée pour l’achèvement du projet')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='active', help_text='Statut actuel du projet (actif, en cours, terminé ou annulé)', max_length=20)),
                ('ai_drafted', models.BooleanField(default=False, help_text='Ce projet a-t-il été rédigé automatiquement par l’assistant IA ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création automatique lors de la publication')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mise à jour automatique à chaque modification')),
                ('client', models.ForeignKey(blank=True, help_text='Utilisateur (client) qui a publié ce projet', limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_posted', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, help_text='Utilisateur (entrepreneur) sélectionné pour ce projet (facultatif)', limit_choices_to={'is_contractor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_awarded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du jalon', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Détails précis sur les travaux associés à ce jalon')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant à verser à la complétion de ce jalon', max_digits=10)),
                ('due_date', models.DateField(help_text='Date limite souhaitée pour compléter ce jalon')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('approved', 'Approuvé'), ('paid', 'Payé')], default='pending', help_text='Statut actuel du jalon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Projet auquel ce jalon est rattaché', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
    ]
