# Generated by Django 4.2.21 on 2025-05-13 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du projet (ex. : Rénovation cuisine)', max_length=255)),
                ('description', models.TextField(help_text='Description détaillée des travaux')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget estimé du client', max_digits=10)),
                ('deadline', models.DateField(help_text='Date limite souhaitée pour la réalisation')),
                ('location', models.CharField(help_text='Adresse ou ville du projet', max_length=255)),
                ('category', models.CharField(help_text='Type de projet (plomberie, toiture, etc.)', max_length=100)),
                ('is_open', models.BooleanField(default=True, help_text='Est-ce que ce projet est encore ouvert aux offres ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
