# Generated by Django 4.2.21 on 2025-05-13 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
        migrations.AddField(
            model_name='project',
            name='ai_drafted',
            field=models.BooleanField(default=False, help_text="Généré automatiquement par l'assistant IA ?"),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='Entrepreneur engagé pour ce projet (facultatif)', limit_choices_to={'is_contractor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='active', help_text='État actuel du projet dans le cycle de vie', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dernière mise à jour des informations du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Budget estimé pour la réalisation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(help_text='Spécialité demandée ou domaine du projet', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='Client qui a publié ce projet', limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='projects_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le projet a été publié'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='Date à laquelle le projet doit idéalement être terminé'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Détails complets fournis par le client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='Adresse, ville ou région du chantier', max_length=255),
        ),
    ]
