# Generated by Django 4.2.21 on 2025-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Adresse courriel utilisée pour se connecter à la plateforme.', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text="Prénom de l'utilisateur (optionnel).", max_length=150)),
                ('last_name', models.CharField(blank=True, help_text="Nom de famille de l'utilisateur (optionnel).", max_length=150)),
                ('phone', models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur.", max_length=15)),
                ('profile_picture', models.ImageField(blank=True, default='core/images/default-avatar.jpg', help_text='Photo de profil affichée dans le profil public.', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, help_text='Courte biographie affichée dans le profil public.')),
                ('city', models.CharField(help_text="Ville de résidence de l'utilisateur.", max_length=100)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', help_text="Langue de l'interface utilisateur (français ou anglais).", max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text="Statut de vérification manuel par l'équipe CONTRACT-IT.")),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text="Date d'inscription de l'utilisateur.")),
                ('company_name', models.CharField(blank=True, help_text="Nom de l'entreprise ou identité professionnelle (optionnel).", max_length=255)),
                ('is_client', models.BooleanField(default=False, help_text="Définit si l'utilisateur peut publier des projets (client).")),
                ('is_contractor', models.BooleanField(default=False, help_text="Définit si l'utilisateur peut proposer ses services (entrepreneur).")),
                ('specialties', models.CharField(blank=True, help_text='Spécialités professionnelles : plomberie, électricité, toiture, etc.', max_length=255)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Tarif horaire proposé par l'entrepreneur (optionnel).", max_digits=8, null=True)),
                ('availability', models.CharField(blank=True, help_text='Disponibilité actuelle (ex. : Disponible en juin).', max_length=100)),
                ('certifications', models.TextField(blank=True, help_text='Certifications détenues (ex. RBQ, ASP, etc.).')),
                ('project_history_count', models.PositiveIntegerField(default=0, help_text='Nombre total de projets publiés par ce client.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
