# Generated by Django 4.2.21 on 2025-05-13 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.CharField(blank=True, help_text='Disponibilité générale : ex. Disponible dès juin', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='certifications',
            field=models.TextField(blank=True, help_text='Certifications professionnelles (ex. RBQ, ASP, etc.)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, help_text="Nom de l'entreprise", max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarif horaire affiché publiquement', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, help_text="Définit si l'utilisateur est un client"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text="Définit si l'utilisateur est un entrepreneur"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est vérifié par l'équipe admin"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', help_text="Langue d'affichage de l'interface", max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project_history_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de projets publiés par le client'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialties',
            field=models.CharField(blank=True, help_text='Domaines de spécialité : ex. Plomberie, Électricité', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Brève biographie affichée sur le profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text="Ville de résidence de l'utilisateur", max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'inscription sur la plateforme"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Adresse courriel pour se connecter et recevoir les notifications', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Photo de profil affichée publiquement', null=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='InternalPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Commentaires ou résultats du projet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(help_text='Projet réalisé via CONTRACT-IT (doit exister dans la plateforme)', on_delete=django.db.models.deletion.CASCADE, related_name='internal_portfolio_item', to='projects.project')),
                ('user', models.ForeignKey(help_text='Utilisateur ayant réalisé ce projet CONTRACT-IT', on_delete=django.db.models.deletion.CASCADE, related_name='internal_portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du projet externe', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du projet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/external/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout dans le portfolio")),
                ('user', models.ForeignKey(help_text='Utilisateur ayant réalisé ce projet externe', on_delete=django.db.models.deletion.CASCADE, related_name='external_portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
